"""
WHAT: Core Domain Contracts (The Ports) for Compsognathus (Compy) V2.
WHY: To enforce the Hexagonal Architecture and Dependency Inversion.
OWNS: Abstract boundaries separating the core domain from external adapters.
DOES NOT OWN: Implementation logic, external dependencies, or concrete state.
SECURITY CONSTRAINTS: External providers must be type-checked against these protocols.
"""

from typing import Protocol, List, Optional, Any, Set, Tuple, Iterator
from enum import Enum
from dataclasses import dataclass

# ---------------------------------------------------------
# TRI-STATE LOGIC (UNKNOWN SEMANTICS INVARIANT)
# ---------------------------------------------------------
class TriState(Enum):
    TRUE = "TRUE"
    FALSE = "FALSE"
    UNKNOWN = "UNKNOWN"

# ---------------------------------------------------------
# EVIDENCE DOMAIN IDENTITIES
# ---------------------------------------------------------
class EvidenceId(str):
    """Strongly typed wrapper for evidence UUIDs."""
    pass

class ProviderId(str):
    """Strongly typed wrapper for provider identification."""
    pass

# ---------------------------------------------------------
# ABSTRACT DOMAIN ENTITIES (Forward Refs for Contracts)
# ---------------------------------------------------------
class IEvidenceNode(Protocol):
    @property
    def id(self) -> EvidenceId: ...
    @property
    def node_type(self) -> str: ...

class IProvenanceRecord(Protocol):
    @property
    def provider_id(self) -> ProviderId: ...
    @property
    def artifact_identity(self) -> str: ...
    @property
    def acquisition_mode(self) -> str: ...

class IObservation(Protocol):
    """A signal generated by a Detector. (A hypothesis, not a fact)."""
    @property
    def detector_id(self) -> ProviderId: ...
    @property
    def target_evidence_id(self) -> EvidenceId: ...

class IInvestigationCandidate(Protocol):
    """A collection of observations supporting a hypothesis."""
    @property
    def candidate_id(self) -> str: ...
    @property
    def independent_evidence_targets(self) -> Set[EvidenceId]: ...
    
class IVerifiedConclusion(Protocol):
    """The result of auditing an investigation candidate."""
    @property
    def status(self) -> TriState: ...
    @property
    def rationale(self) -> str: ...

class CapabilityStatus(Enum):
    SUCCESS = "SUCCESS"
    FAILED = "FAILED"
    UNAVAILABLE = "UNAVAILABLE"
    PARTIAL = "PARTIAL"

class ProviderCapability(Enum):
    PROCESS_LIST = "PROCESS_LIST"
    VAD_INFO = "VAD_INFO"
    MEMORY_CONTENT = "MEMORY_CONTENT"
    HANDLES = "HANDLES"
    MODULES = "MODULES"

class IProviderResult(Protocol):
    @property
    def capability_status(self) -> CapabilityStatus: ...
    @property
    def available_capabilities(self) -> Set[ProviderCapability]: ...
    @property
    def extracted_dtos(self) -> Tuple[Any, ...]: ...
    @property
    def capability_failures(self) -> Tuple[str, ...]: ...
    @property
    def provenance(self) -> IProvenanceRecord: ...

@dataclass(frozen=True)
class ProviderResult(IProviderResult):
    """Concrete immutable implementation of IProviderResult."""
    _capability_status: CapabilityStatus
    _available_capabilities: frozenset[ProviderCapability]
    _extracted_dtos: Tuple[Any, ...]
    _capability_failures: Tuple[str, ...]
    _provenance: IProvenanceRecord

    @property
    def capability_status(self) -> CapabilityStatus:
        return self._capability_status

    @property
    def available_capabilities(self) -> Set[ProviderCapability]:
        # Return as set to satisfy interface, though internal is frozenset
        return set(self._available_capabilities)

    @property
    def extracted_dtos(self) -> Tuple[Any, ...]:
        return self._extracted_dtos

    @property
    def capability_failures(self) -> Tuple[str, ...]:
        return self._capability_failures

    @property
    def provenance(self) -> IProvenanceRecord:
        return self._provenance

class IDetectorResult(Protocol):
    @property
    def status(self) -> CapabilityStatus: ...
    @property
    def observations(self) -> List[IObservation]: ...
    @property
    def failure_reason(self) -> Optional[str]: ...

# ---------------------------------------------------------
# CONTENT STREAMING SEMANTICS
# ---------------------------------------------------------
class ContentReadStatus(Enum):
    SUCCESS = "SUCCESS"
    PARTIAL = "PARTIAL"
    FAILED = "FAILED"
    UNAVAILABLE = "UNAVAILABLE"

class AddressSpace(Enum):
    VIRTUAL = "VIRTUAL"
    PHYSICAL = "PHYSICAL"

@dataclass(frozen=True)
class EvidenceContentReference:
    target_evidence_id: EvidenceId
    address_space: AddressSpace
    owner_context_id: Optional[EvidenceId] = None

@dataclass(frozen=True)
class ContentReadChunk:
    offset: int
    data: bytes

@dataclass(frozen=True)
class ContentReadGap:
    offset: int
    length: int
    reason: str

class IContentAccessor(Protocol):
    def stream_bytes(
        self,
        ref: EvidenceContentReference,
        offset: int,
        length: int,
        chunk_size: int = 1024 * 1024
    ) -> Iterator[ContentReadChunk | ContentReadGap]: ...

# ---------------------------------------------------------
# THE PORTS (INTERFACES)
# ---------------------------------------------------------

class ICollector(Protocol):
    """
    Contract for extracting raw telemetry.
    Implemented by: MockCollector, VolatilityCollector, LiveCollector.
    """
    def provider_id(self) -> ProviderId: ...
    def extract_evidence(self) -> IProviderResult: ...

class ILedgerWrite(Protocol):
    """Contract for writing immutable facts."""
    def append_node(self, node: IEvidenceNode, provenance: IProvenanceRecord) -> None: ...
    def append_relationship(self, source: EvidenceId, target: EvidenceId, relation_type: str, provenance: IProvenanceRecord) -> None: ...

class ILedgerQuery(Protocol):
    """Contract for querying the immutable ledger."""
    def get_node(self, evidence_id: EvidenceId) -> Optional[IEvidenceNode]: ...
    def get_all_nodes(self) -> List[IEvidenceNode]: ...

class IGraphQuery(Protocol):
    """Contract for querying structural facts (not hypotheses)."""
    def get_children(self, parent_id: EvidenceId, relation_type: str) -> List[IEvidenceNode]: ...
    def get_parent(self, child_id: EvidenceId, relation_type: str) -> Optional[IEvidenceNode]: ...

class IDetector(Protocol):
    """
    Contract for generating observations based on evidence.
    Cannot modify evidence. Cannot execute response.
    """
    def provider_id(self) -> ProviderId: ...
    def required_capabilities(self) -> Set[ProviderCapability]: ...
    def evaluate(self, ledger: ILedgerQuery, graph: IGraphQuery, content: IContentAccessor) -> IDetectorResult: ...

class ICorroborator(Protocol):
    """Contract for grouping independent observations into hypotheses."""
    def evaluate(self, observations: List[IObservation], graph: IGraphQuery) -> List[IInvestigationCandidate]: ...

class IVerifier(Protocol):
    """Contract for logically auditing hypotheses."""
    def verify(self, candidate: IInvestigationCandidate, ledger: ILedgerQuery, graph: IGraphQuery) -> IVerifiedConclusion: ...

class IGovernanceGate(Protocol):
    """Contract for policy/human approval of response plans."""
    def request_approval(self, conclusion: IVerifiedConclusion) -> bool: ...
